name: CD_pipelne

on:
  push:
    branches: [ main ]
  # workflow_run:
  #   types:
  #     - completed
  #   workflows: ["CI workflow"]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Pull dockerhub image
      run: |
        docker pull jatoroe/todoapp:latest

    - name: make docker-compose up
      run: |
       ls -a
       docker-compose down
       docker container prune
       docker-compose up -d
       docker ps