name: CI workflow

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./app/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: test with test inside app
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: test app
      working-directory: ${{ env.working-directory }}  
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi

    - name: Test the app
      working-directory: ${{ env.working-directory }} 
      run: npm test
      env:
        NODE_ENV: test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Push Docker image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./app/Dockerfile
        push: true
        tags: "${{ env.DOCKER_USERNAME }}/todoapp:latest,${{ env.GITHUB_SHA }}"